export const COMPANY_TYPES = [
	{ value: "Product provider", label: "Product provider" },
	{ value: "Service provider", label: "Service provider" }
];

export const N_EMPOYEES = [
	{ value: "3", label: "3" },
	{ value: "8", label: "8" },
	{ value: "15", label: "15" },
	{ value: "30", label: "30" },
	{ value: "50", label: "50" },
	{ value: "80", label: "80" },
	{ value: "120", label: "120" },
	{ value: "200", label: "200" },
	{ value: "400", label: "400" },
	{ value: "1000", label: "1000" },
	{ value: "3000", label: "3000" },
	{ value: "10000", label: "10000" }
];

export const REVENUES = [
	{ value: "0", label: "0" },
	{ value: "500K", label: "500K" },
	{ value: "1M", label: "1M" },
	{ value: "2M", label: "2M" },
	{ value: "4M", label: "4M" },
	{ value: "8M", label: "8M" },
	{ value: "15M", label: "15M" },
	{ value: "30M", label: "30M" },
	{ value: "60M", label: "60M" },
	{ value: "100M", label: "100M" },
	{ value: "150M", label: "150M" },
	{ value: "300M", label: "300M" }
];

export const ATECO_CODES = [
	{ value: "24.1", label: "24.1" },
	{ value: "24.2", label: "24.2" },
	{ value: "24.31", label: "24.31" },
	{ value: "24.32", label: "24.32" },
	{ value: "24.33", label: "24.33" },
	{ value: "24.34", label: "24.34" },
	{ value: "24.41", label: "24.41" },
	{ value: "24.42", label: "24.42" },
	{ value: "24.43", label: "24.43" },
	{ value: "24.44", label: "24.44" },
	{ value: "24.45", label: "24.45" },
	{ value: "24.51", label: "24.51" },
	{ value: "24.52", label: "24.52" },
	{ value: "24.53", label: "24.53" },
	{ value: "24.54", label: "24.54" },
	{ value: "25.11", label: "25.11" },
	{ value: "25.12.1", label: "25.12.1" },
	{ value: "25.21", label: "25.21" },
	{ value: "25.29", label: "25.29" },
	{ value: "25.3", label: "25.3" },
	{ value: "25.5", label: "25.5" },
	{ value: "25.61", label: "25.61" },
	{ value: "25.62", label: "25.62" },
	{ value: "25.7", label: "25.7" },
	{ value: "25.9", label: "25.9" },
	{ value: "26.12", label: "26.12" },
	{ value: "26.2", label: "26.2" },
	{ value: "26.30.1", label: "26.30.1" },
	{ value: "26.51.10", label: "26.51.10" },
	{ value: "26.52", label: "26.52" },
	{ value: "26.70.11", label: "26.70.11" },
	{ value: "28 (tutti/all)", label: "28 (tutti/all)" },
	{ value: "29.1", label: "29.1" },
	{ value: "29.2", label: "29.2" },
	{ value: "29.3", label: "29.3" },
	{ value: "33.11", label: "33.11" },
	{ value: "33.2", label: "33.2" },
	{ value: "46.61", label: "46.61" },
	{ value: "46.62", label: "46.62" },
	{ value: "46.63", label: "46.63" },
	{ value: "46.64", label: "46.64" },
	{ value: "46.69.20", label: "46.69.20" },
	{ value: "46.69.91", label: "46.69.91" },
	{ value: "46.69.94", label: "46.69.94" },
	{ value: "46.69.99", label: "46.69.99" }
];

export const REGIONS = [
	{ value: "Abruzzo", label: "Abruzzo" },
	{ value: "Basilicata", label: "Basilicata" },
	{ value: "Calabria", label: "Calabria" },
	{ value: "Campania", label: "Campania" },
	{ value: "Emilia Romagna", label: "Emilia Romagna" },
	{ value: "Friuli-Venezia Giulia", label: "Friuli-Venezia Giulia" },
	{ value: "Lazio", label: "Lazio" },
	{ value: "Liguria", label: "Liguria" },
	{ value: "Lombardia", label: "Lombardia" },
	{ value: "Marche", label: "Marche" },
	{ value: "Molise", label: "Molise" },
	{ value: "Piemonte", label: "Piemonte" },
	{ value: "Puglia", label: "Puglia" },
	{ value: "Sardegna", label: "Sardegna" },
	{ value: "Sicilia", label: "Sicilia" },
	{ value: "Trentino-Alto Adige", label: "Trentino-Alto Adige" },
	{ value: "Toscana", label: "Toscana" },
	{ value: "Umbria", label: "Umbria" },
	{ value: "Valle d'Aosta", label: "Valle d'Aosta" },
	{ value: "Veneto", label: "Veneto" }
];

export const CITIES = [
	{ value: "Chieti", label: "Chieti" },
	{ value: "L'Aquila", label: "L'Aquila" },
	{ value: "Pescara", label: "Pescara" },
	{ value: "Teramo", label: "Teramo" },
	{ value: "Matera", label: "Matera" },
	{ value: "Potenza", label: "Potenza" },
	{ value: "Catanzaro", label: "Catanzaro" },
	{ value: "Cosenza", label: "Cosenza" },
	{ value: "Crotone", label: "Crotone" },
	{ value: "Reggio Calabria", label: "Reggio Calabria" },
	{ value: "Vibo Valentia", label: "Vibo Valentia" },
	{ value: "Avellino", label: "Avellino" },
	{ value: "Benevento", label: "Benevento" },
	{ value: "Caserta", label: "Caserta" },
	{ value: "Napoli", label: "Napoli" },
	{ value: "Salerno", label: "Salerno" },
	{ value: "Bologna", label: "Bologna" },
	{ value: "Cesena", label: "Cesena" },
	{ value: "Ferrara", label: "Ferrara" },
	{ value: "Forlì", label: "Forlì" },
	{ value: "Modena", label: "Modena" },
	{ value: "Parma", label: "Parma" },
	{ value: "Piacenza", label: "Piacenza" },
	{ value: "Ravenna", label: "Ravenna" },
	{ value: "Reggio Emilia", label: "Reggio Emilia" },
	{ value: "Rimini", label: "Rimini" },
	{ value: "Gorizia", label: "Gorizia" },
	{ value: "Pordenone", label: "Pordenone" },
	{ value: "Trieste", label: "Trieste" },
	{ value: "Udine", label: "Udine" },
	{ value: "Frosinone", label: "Frosinone" },
	{ value: "Latina", label: "Latina" },
	{ value: "Rieti", label: "Rieti" },
	{ value: "Roma", label: "Roma" },
	{ value: "Viterbo", label: "Viterbo" },
	{ value: "Genova", label: "Genova" },
	{ value: "Imperia", label: "Imperia" },
	{ value: "La Spezia", label: "La Spezia" },
	{ value: "Savona", label: "Savona" },
	{ value: "Bergamo", label: "Bergamo" },
	{ value: "Brescia", label: "Brescia" },
	{ value: "Como", label: "Como" },
	{ value: "Cremona", label: "Cremona" },
	{ value: "Lecco", label: "Lecco" },
	{ value: "Lodi", label: "Lodi" },
	{ value: "Mantova", label: "Mantova" },
	{ value: "Milano", label: "Milano" },
	{ value: "Monza", label: "Monza" },
	{ value: "Pavia", label: "Pavia" },
	{ value: "Sondrio", label: "Sondrio" },
	{ value: "Varese", label: "Varese" },
	{ value: "Ancona", label: "Ancona" },
	{ value: "Ascoli Piceno", label: "Ascoli Piceno" },
	{ value: "Fermo", label: "Fermo" },
	{ value: "Macerata", label: "Macerata" },
	{ value: "Pesaro", label: "Pesaro" },
	{ value: "Urbino", label: "Urbino" },
	{ value: "Campobasso", label: "Campobasso" },
	{ value: "Isernia", label: "Isernia" },
	{ value: "Alessandria", label: "Alessandria" },
	{ value: "Asti", label: "Asti" },
	{ value: "Biella", label: "Biella" },
	{ value: "Cuneo", label: "Cuneo" },
	{ value: "Novara", label: "Novara" },
	{ value: "Torino", label: "Torino" },
	{ value: "Verbania", label: "Verbania" },
	{ value: "Vercelli", label: "Vercelli" },
	{ value: "Andria", label: "Andria" },
	{ value: "Bari", label: "Bari" },
	{ value: "Barletta", label: "Barletta" },
	{ value: "Brindisi", label: "Brindisi" },
	{ value: "Foggia", label: "Foggia" },
	{ value: "Lecce", label: "Lecce" },
	{ value: "Taranto", label: "Taranto" },
	{ value: "Trani", label: "Trani" },
	{ value: "Cagliari", label: "Cagliari" },
	{ value: "Carbonia", label: "Carbonia" },
	{ value: "Nuoro", label: "Nuoro" },
	{ value: "Oristano", label: "Oristano" },
	{ value: "Sassari", label: "Sassari" },
	{ value: "Agrigento", label: "Agrigento" },
	{ value: "Caltanissetta", label: "Caltanissetta" },
	{ value: "Catania", label: "Catania" },
	{ value: "Enna", label: "Enna" },
	{ value: "Messina", label: "Messina" },
	{ value: "Palermo", label: "Palermo" },
	{ value: "Ragusa", label: "Ragusa" },
	{ value: "Siracusa", label: "Siracusa" },
	{ value: "Trapani", label: "Trapani" },
	{ value: "Bolzano", label: "Bolzano" },
	{ value: "Trento", label: "Trento" },
	{ value: "Arezzo", label: "Arezzo" },
	{ value: "Firenze", label: "Firenze" },
	{ value: "Grosseto", label: "Grosseto" },
	{ value: "Livorno", label: "Livorno" },
	{ value: "Lucca", label: "Lucca" },
	{ value: "Massa", label: "Massa" },
	{ value: "Pisa", label: "Pisa" },
	{ value: "Pistoia", label: "Pistoia" },
	{ value: "Prato", label: "Prato" },
	{ value: "Siena", label: "Siena" },
	{ value: "Perugia", label: "Perugia" },
	{ value: "Terni", label: "Terni" },
	{ value: "Aosta", label: "Aosta" },
	{ value: "Belluno", label: "Belluno" },
	{ value: "Padova", label: "Padova" },
	{ value: "Rovigo", label: "Rovigo" },
	{ value: "Treviso", label: "Treviso" },
	{ value: "Venezia", label: "Venezia" },
	{ value: "Verona", label: "Verona" },
	{ value: "Vicenza", label: "Vicenza" }
];
